// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotTrack.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SpotTrack.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617065047_AddExerciseBlocksToRoutines")]
    partial class AddExerciseBlocksToRoutines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_admins");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reservations");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_reservation_requests");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("i_x_reservation_requests_reservation_id");

                    b.ToTable("reservation_requests");
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_routines");

                    b.ToTable("routines");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_admins_email");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_clients_email");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", b =>
                {
                    b.HasOne("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", null)
                        .WithOne("Request")
                        .HasForeignKey("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_reservation_requests_reservations_reservation_id");
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.Routine", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.ClientId", "ClientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("client_id");

                            b1.HasKey("Id")
                                .HasName("p_k_routines");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_routines_client_id");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_routines_routines_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.RoutineName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("routine_name");

                            b1.HasKey("Id")
                                .HasName("p_k_routines");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_routines_routines_id");
                        });

                    b.OwnsMany("SpotTrack.Platform.Routines.Domain.Model.Entities.ExerciseBlock", "ExerciseBlocks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasColumnName("block_order");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("exercise_type");

                            b1.Property<int>("routine_id")
                                .HasColumnType("int")
                                .HasColumnName("routine_id");

                            b1.HasKey("Id")
                                .HasName("p_k_exercise_blocks");

                            b1.HasIndex("routine_id")
                                .HasDatabaseName("i_x_exercise_blocks_routine_id");

                            b1.ToTable("exercise_blocks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("routine_id")
                                .HasConstraintName("f_k_exercise_blocks_routines_routine_id");

                            b1.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.ExerciseName", "Name", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("varchar(100)")
                                        .HasColumnName("exercise_name");

                                    b2.HasKey("Id")
                                        .HasName("p_k_exercise_blocks");

                                    b2.ToTable("exercise_blocks");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("f_k_exercise_blocks_exercise_blocks_id");
                                });

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.Navigation("ClientId")
                        .IsRequired();

                    b.Navigation("ExerciseBlocks");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Navigation("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
