// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotTrack.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SpotTrack.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619183950_AddMaintenanceTechnicalTicket")]
    partial class AddMaintenanceTechnicalTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_equipment");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_gyms");

                    b.ToTable("gyms");
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("gym_id")
                        .HasColumnType("int")
                        .HasColumnName("gym_id");

                    b.HasKey("Id")
                        .HasName("p_k_branches");

                    b.HasIndex("gym_id")
                        .HasDatabaseName("i_x_branches_gym_id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("branch_id")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.HasKey("Id")
                        .HasName("p_k_zones");

                    b.HasIndex("branch_id")
                        .HasDatabaseName("i_x_zones_branch_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("SpotTrack.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SpotTrack.Platform.Maintenances.Domain.Model.Aggregates.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("requested_by_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_maintenances");

                    b.ToTable("maintenances");
                });

            modelBuilder.Entity("SpotTrack.Platform.Maintenances.Domain.Model.Aggregates.TechnicalTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<int>("MaintenanceId")
                        .HasColumnType("int")
                        .HasColumnName("maintenance_id");

                    b.Property<string>("MaintenanceProgress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maintenance_progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_technical_tickets");

                    b.ToTable("technical_tickets");
                });

            modelBuilder.Entity("SpotTrack.Platform.Memberships.Domain.Model.Aggregates.BranchAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("GrantedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("granted_by_admin_id");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("membership_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_branch_accesses");

                    b.ToTable("branch_accesses");
                });

            modelBuilder.Entity("SpotTrack.Platform.Memberships.Domain.Model.Aggregates.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_memberships");

                    b.ToTable("memberships");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_admins");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reservations");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_reservation_requests");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("i_x_reservation_requests_reservation_id");

                    b.ToTable("reservation_requests");
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_routines");

                    b.ToTable("routines");
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.RoutineSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("RoutineId")
                        .HasColumnType("int")
                        .HasColumnName("routine_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_routine_sessions");

                    b.ToTable("routine_sessions");
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Equipment", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.EquipmentName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_equipment");

                            b1.ToTable("equipment");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_equipment_equipment_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.ZoneId", "ZoneId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("zone_id");

                            b1.HasKey("Id")
                                .HasName("p_k_equipment");

                            b1.ToTable("equipment");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_equipment_equipment_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ZoneId")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Gym", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("district");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("street");

                            b1.HasKey("Id")
                                .HasName("p_k_gyms");

                            b1.ToTable("gyms");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_gyms_gyms_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.GymName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_gyms");

                            b1.ToTable("gyms");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_gyms_gyms_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Entities.Branch", b =>
                {
                    b.HasOne("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Gym", null)
                        .WithMany("Branches")
                        .HasForeignKey("gym_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_branches_gyms_gym_id");

                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("district");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("street");

                            b1.HasKey("Id")
                                .HasName("p_k_branches");

                            b1.ToTable("branches");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_branches_branches_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.BranchName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_branches");

                            b1.ToTable("branches");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_branches_branches_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Entities.Zone", b =>
                {
                    b.HasOne("SpotTrack.Platform.Gyms.Domain.Model.Entities.Branch", null)
                        .WithMany("Zones")
                        .HasForeignKey("branch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_zones_branches_branch_id");

                    b.OwnsOne("SpotTrack.Platform.Gyms.Domain.Model.ValueObjects.ZoneName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_zones");

                            b1.ToTable("zones");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_zones_zones_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_admins_email");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.Navigation("Dni");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_clients_email");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.Navigation("Dni");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", b =>
                {
                    b.HasOne("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", null)
                        .WithOne("Request")
                        .HasForeignKey("SpotTrack.Platform.Reservations.Domain.Model.Entities.ReservationRequest", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_reservation_requests_reservations_reservation_id");
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.Routine", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.ClientId", "ClientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("client_id");

                            b1.HasKey("Id")
                                .HasName("p_k_routines");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_routines_client_id");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_routines_routines_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.RoutineName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("routine_name");

                            b1.HasKey("Id")
                                .HasName("p_k_routines");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_routines_routines_id");
                        });

                    b.OwnsMany("SpotTrack.Platform.Routines.Domain.Model.Entities.ExerciseBlock", "ExerciseBlocks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasColumnName("block_order");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("exercise_type");

                            b1.Property<int>("routine_id")
                                .HasColumnType("int")
                                .HasColumnName("routine_id");

                            b1.HasKey("Id")
                                .HasName("p_k_exercise_blocks");

                            b1.HasIndex("routine_id")
                                .HasDatabaseName("i_x_exercise_blocks_routine_id");

                            b1.ToTable("exercise_blocks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("routine_id")
                                .HasConstraintName("f_k_exercise_blocks_routines_routine_id");

                            b1.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.ExerciseName", "Name", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("varchar(100)")
                                        .HasColumnName("exercise_name");

                                    b2.HasKey("Id")
                                        .HasName("p_k_exercise_blocks");

                                    b2.ToTable("exercise_blocks");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("f_k_exercise_blocks_exercise_blocks_id");
                                });

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.Navigation("ClientId")
                        .IsRequired();

                    b.Navigation("ExerciseBlocks");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Routines.Domain.Model.Aggregates.RoutineSession", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Routines.Domain.Model.ValueObjects.ClientId", "ClientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("client_id");

                            b1.HasKey("Id")
                                .HasName("p_k_routine_sessions");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_routine_sessions_client_id");

                            b1.ToTable("routine_sessions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_routine_sessions_routine_sessions_id");
                        });

                    b.Navigation("ClientId")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Aggregates.Gym", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("SpotTrack.Platform.Gyms.Domain.Model.Entities.Branch", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SpotTrack.Platform.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Navigation("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
